namespace SpriteKind {
    export const kernel = SpriteKind.create()
}
function promptLoop () {
    cmd = game.askForString("root@archiso:" + cwd + "# ")
    runCommand(cmd)
    promptLoop()
}
// Function to run commands
function runCommand (command: string) {
    index = busyboxCommands.indexOf(command)
    if (index >= 0) {
        game.splash(busyboxOutputs[index])
    } else {
        game.splash(`sh: ${command}: command not found`)
    }
}
let index = 0
let cmd = ""
let busyboxOutputs: string[] = []
let busyboxCommands: string[] = []
let cwd = ""
cwd = "/"
cwd = "/"
busyboxCommands = [
"echo $HOME",
"ash",
"awk",
"basename",
"blkid",
"bunzip2",
"bzcat",
"cat",
"chgrp",
"chmod",
"chown",
"cp",
"crond",
"cut",
"date",
"dd",
"df",
"diff",
"dirname",
"dmesg",
"du",
"echo",
"env",
"expr",
"false",
"fgrep",
"find",
"free",
"fsck",
"getopt",
"grep",
"gunzip",
"gzip",
"head",
"hostname",
"id",
"ifconfig",
"init",
"insmod",
"ip",
"kill",
"killall",
"ln",
"loadkmap",
"login",
"ls",
"lsmod",
"md5sum",
"mkdir",
"mknod",
"mkfifo",
"mktemp",
"mount",
"mv",
"nc",
"netstat",
"nslookup",
"passwd",
"ping",
"ps",
"pwd",
"readlink",
"rm",
"rmdir",
"sed",
"seq",
"sh",
"sleep",
"sort",
"stat",
"strings",
"stty",
"tail",
"tar",
"tee",
"test",
"time",
"top",
"touch",
"true",
"umount",
"uname",
"uniq",
"unlink",
"uptime",
"users",
"vi",
"watch",
"wc",
"who",
"whoami",
"yes",
"ar",
"base32",
"base64",
"basename",
"bzip2",
"cal",
"chroot",
"cmp",
"comm",
"cpio",
"cut",
"date",
"ddrescue",
"df",
"diff",
"dirname",
"dmesg",
"dos2unix",
"du",
"echo",
"ed",
"egrep",
"env",
"expand",
"expr"
]
busyboxOutputs = [
"echo $HOME: /root",
"/bin\n/boot\n/dev\n/etc\n/home\n/lib\n/lib64\n/media\n/mnt\n/opt\n/proc\n/root\n/run\n/sbin\n/srv\n/sys\n/tmp\n/usr\n/var",
"awk: no input files",
"basename: missing operand",
"blkid: /dev/sda1: UUID=\"1234-ABCD\" TYPE=\"ext4\"",
"bunzip2: can't open input.bz2: No such file or directory",
"bzcat: no such file or directory",
"cat: missing file operand",
"chgrp: missing operand",
"chmod: missing operand",
"chown: missing operand",
"cp: missing destination file operand after ''",
"crond: no crontab",
"cut: no input files",
"date: Fri Nov 22 12:00:00 UTC 2025",
"dd: missing operand",
"df: Filesystem     1K-blocks    Used Available Use% Mounted on\n/dev/sda1       8060928  148580  7912348   2% /",
"diff: missing operand",
"dirname: missing operand",
"dmesg: [    0.000000] Linux version 6.1.14 (gcc 12.2.0)",
"du: missing operand",
"echo: Hello World\nHello World",
"env:",
"expr: syntax error",
"false",
"fgrep: no input files",
"find: . -name '*'\n./bin\n./boot\n./dev\n./etc\n./home\n./lib\n./lib64\n./media\n./mnt\n./opt\n./proc\n./root\n./run\n./sbin\n./srv\n./sys\n./tmp\n./usr\n./var",
"free: total        used        free      shared  buff/cache   available\nMem:       8192MB      1024MB      6144MB       128MB      1024MB      7000MB\nSwap:      2048MB        0MB      2048MB",
"fsck: no errors",
"getopt: missing operand",
"grep: no input files",
"gunzip: can't open file.gz: No such file or directory",
"gzip: can't open file: No such file or directory",
"head: missing file operand",
"hostname: archiso",
"id: uid=0(root) gid=0(root) groups=0(root)",
"ifconfig: eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500\n        inet 192.168.0.100  netmask 255.255.255.0  broadcast 192.168.0.255",
"init: switching to runlevel 3",
"insmod: ERROR: could not insert module",
"ip: usage: ip [ OPTIONS ] OBJECT { COMMAND | help }",
"kill: usage: kill [-s sigspec] pid | jobspec ...",
"killall: no process found",
"ln: missing file operand",
"loadkmap: usage: loadkmap <keymap>",
"login: login:",
"ls: bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var",
"lsmod: Module                  Size  Used by\next4                  918  1\nipv6                  12345 2",
"md5sum: missing operand",
"mkdir: missing operand",
"mknod: missing operand",
"mkfifo: missing operand",
"mktemp: failed to create temp file",
"mount: /dev/sda1 on / type ext4 (rw,relatime,data=ordered)",
"mv: missing destination file operand after ''",
"nc: usage: nc [-options] hostname port",
"netstat: Proto Recv-Q Send-Q Local Address           Foreign Address         State\ntcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN",
"nslookup: can't resolve 'example.com'",
"passwd: password for root changed successfully",
"ping: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.\n64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=10.5 ms",
"ps: PID   USER     COMMAND\n1     root     /sbin/init\n312   root     /sbin/systemd\n450   user     /bin/bash",
"pwd: /",
"readlink: missing operand",
"rm: missing operand",
"rmdir: missing operand",
"sed: no input files",
"seq: missing operand",
"sh: sh-5.2$",
"sleep: usage: sleep NUMBER[SUFFIX]",
"sort: no input files",
"stat: missing operand",
"strings: no input file",
"stty: stdin isn't a terminal",
"tail: no input files",
"tar: Cowardly refusing to create an empty archive",
"tee: missing operand",
"test: missing operand",
"time: real 0m0.001s user 0m0.000s sys 0m0.001s",
"top: top - 12:00:00 up 1:23,  1 user,  load average: 0.01, 0.05, 0.10",
"touch: missing file operand",
"true",
"umount: /mnt: not mounted",
"uname: Linux",
"uniq: no input files",
"unlink: missing operand",
"uptime:  12:00:00 up  1:23,  1 user,  load average: 0.01, 0.05, 0.10",
"users: root",
"vi: /",
"watch: missing operand",
"wc: missing operand",
"who: root tty1",
"whoami: root",
"yes: y\ny\ny\ny\ny\ny\ny\ny\ny\ny",
"ar: missing operand",
"base32: missing operand",
"base64: missing operand",
"basename: missing operand",
"bzip2: can't open input file",
"cal: November 2025",
"chroot: missing operand",
"cmp: missing operand",
"comm: missing operand",
"cpio: missing operand",
"cut: missing operand",
"date: Fri Nov 22 12:00:00 UTC 2025",
"ddrescue: missing operand",
"df: Filesystem     1K-blocks    Used Available Use% Mounted on\n/dev/sda1       8060928  148580  7912348   2% /",
"diff: missing operand",
"dirname: missing operand",
"dmesg: [    0.000000] Linux version 6.1.14",
"dos2unix: missing operand",
"du: missing operand",
"echo: Hello World\nHello World",
"ed: no input files",
"egrep: missing operand",
"env:",
"expand: missing operand",
"expr: syntax error"
]
function setup() {}
cwd = "/"
let mySprite = sprites.create(assets.image`myImage`, SpriteKind.kernel)
mySprite.scale = 6
let bootMessages = [
"[ kernel init ]",
"Linux version 6.1.14 (gcc version 12.2.0) #1 SMP PREEMPT",
"Command line: BOOT_IMAGE=/vmlinuz-6.1.14 root=/dev/sda1 rw quiet",
"x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point regs'",
"x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'",
"CPU: Intel(R) Core(TM) i5 CPU @ 2.40GHz",
"Performance Events: core PMU driver initialized",
"ACPI: RSDP 0x00000000000F0420 000024 (v02 ACPIAM)",
"ACPI: XSDT 0x00000000BFEF0100 000084 (v01 A M I OEMXSDT)",
"ACPI: APIC 0x00000000BFEF1010 0000BC (v03 AMI  OEMAPIC)",
"ACPI: HPET 0x00000000BFEF10D0 000038 (v01 AMI  OEMHPET)",
"NUMA: No NUMA configuration found",
"Detected 8192MB of physical memory",
"Memory: 7912348K/8060928K available",
"Kernel/User page tables isolation: enabled",
"Built 1 zonelists, mobility grouping on",
"CPU: Using scheduler topology for CPU 0",
"Initializing cgroup subsys cpuset",
"Initializing cgroup subsys cpu",
"Initializing cgroup subsys cpuacct",
"ftrace: allocating 35608 entries in 140 pages",
"SRBDS: Mitigation: Microcode",
"PCI: Using configuration type 1",
"PCI: Probing PCI hardware",
"pci 0000:00:1f.2: AHCI controller",
"ahci 0000:00:1f.2: AHCI 0001.0301 32 slots 6 ports",
"xhci_hcd 0000:00:14.0: xHCI Host Controller",
"SCSI subsystem initialized",
"ata1: SATA link up 3.0 Gbps",
"ata1.00: ATA-9: ST500LM021, firmware 0001",
"EXT4-fs (sda1): mounted filesystem with ordered data mode",
"VFS: Mounted root (ext4 filesystem) on device 8:1",
"Freeing unused kernel image memory: 1536K",
"Run /sbin/init as init process",
"systemd[1]: systemd v252 running in system mode",
"systemd[1]: Detected architecture x86-64",
"systemd[1]: Started udev Kernel Device Manager",
"systemd-udevd[312]: Using default interface naming scheme 'v247'",
"e1000e 0000:00:19.0 eth0: registered",
"IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready",
"systemd[1]: Started Network Manager",
"systemd[1]: Reached target Multi-User System",
"systemd[1]: Started Getty on tty1",
"systemd[1]: Started Login Service",
"audit: type=1130 audit(0.0:1): service=systemd-logind started",
"eth0: Link is Up - 100Mbps Full Duplex",
"systemd[1]: Finished Daily Cleanup of Temporary Directories",
"linux-machine login:"
]
for (let msg of bootMessages) {
    game.splash(msg)
}
promptLoop()
function startvm () {
    console.log("starting VM");
    setup()
    setup()
}